import "pkg:/source/enums/KeyCode.bs"
import "pkg:/source/utils/misc.bs"

sub init()
end sub

function onKeyEvent(key as string, press as boolean) as boolean
    if not press then return false

    ' If we are on the 1st channel and the schedule isn't fully loaded yet, disallow moving up before index 0
    if isStringEqual(key, KeyCode.UP)
        if m.top.channelFocused = 0
            if not m.top.isLoaded then return true
        end if
    end if

    return false
end function
