name: Bug Report
description: Report a bug with the software.
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        # <span style="color:red">If your bug involves media playback, you MUST include a link to a sample of the media that exhibits the bug, otherwise the ticket will be closed !!!</span>

  - type: checkboxes
    id: before-posting
    attributes:
      label: "This issue respects the following points:"
      description: All conditions are **required**.
      options:
        - label: This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-roku/issues?q=is%3Aissue) _(I've searched open and closed issues)_.
          required: true
        - label: I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
          required: true
        - label: This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.
          required: true

  - type: markdown
    attributes:
      value: |
        ## Software Versions
  - type: input
    id: jellyfin_server_version
    attributes:
      label: Jellyfin Server Version
      placeholder: "e.g., 10.9.11 or 10.10.3"
    validations:
      required: true
  - type: input
    id: roku_version
    attributes:
      label: Roku Client Version
      placeholder: "e.g., 2.1.8 or 2.2.5"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug Information
  - type: textarea
    id: bug_description
    attributes:
      label: Bug Description
      description: Provide a clear and concise description of what the bug is.
      placeholder: "When playing a movie via the «Resume from» context menu, I get the error message «xyz»"
    validations:
      required: true
  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. Bug occurs
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Provide a clear and concise description of what you expected to happen.
      placeholder: "Describe what you expected to happen."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please paste any logs here.
      placeholder: "Paste logs here, if available."
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: "Paste Screenshots here, if available."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Connection Information
  - type: dropdown
    id: server_access_relativity
    attributes:
      label: Is the server local or remote?
      options:
        - Please select...
        - local
        - remote
      default: 0
    validations:
      required: false
  - type: dropdown
    id: server_access_protocol
    attributes:
      label: Is the server connection HTTP or HTTPS?
      options:
        - Please select...
        - http
        - https
      default: 0
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Additional
  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
