import "pkg:/source/enums/ItemType.bs"
import "pkg:/source/utils/misc.bs"

sub setFields()
    if not isValid(m.top.json) then return
    datum = m.top.json

    m.top.id = datum.id
    m.top.type = ItemType.EPISODE
    m.top.title = datum.name
    m.top.showID = datum.SeriesID
    m.top.seasonID = datum.SeasonID
    m.top.overview = datum.overview
    isFavorite = chainLookup(datum, "UserData.isFavorite")
    played = chainLookup(datum, "UserData.played")
    if isValid(isFavorite) then m.top.favorite = isFavorite
    if isValid(played)
        m.top.played = played
        m.top.watched = played
    end if
end sub

sub setPoster()
    if isValid(m.top.image)
        m.top.posterURL = m.top.image.url
    else
        m.top.posterURL = ""
    end if
end sub
